#	Eventually Deluxe for Jekyll (https://github.com/dcsjapan/jekyll-theme-eventually-deluxe)
#	by Dominion (https://www.dcsjapan.com)
#	Free for personal and commercial use under CC-BY-3.0 (https://creativecommons.org/licenses/by/3.0/)
#
#	Based on Eventually (https://html5up.net/eventually)
#	by HTML5 UP (https://html5up.net | @ajlkn)
#	Free for personal and commercial use under CC-BY-3.0 (https://html5up.net/license)


### SITE SETTINGS

# The title of your site; used in title tags and <h1> headers. Defaults to "Eventually Deluxe".
title:             Site Title

# The site description; used in site description meta tags.
description:       A detailed description of what visitors can expect to find in the site

# The default language for all pages in the site; defaults to "en".
lang:              en

# The base protocol and hostname for your site, e.g. "http://example.com".
url:               ""

# The subpath for a site that isn't in the web root, e.g. "/blog".
baseurl:           ""

# The path where image files are stored; defaults to '/assets/images/'.
# You may also specify an external server as an absolute URL.
# NOTE: Set this to "/demo/images/" to see the images included in the demo site.
image_source:      /demo/images/  

# The default format for dates displayed by the site.
date_format:       "%B %d, %Y"

# The string that delimits the end of post excerpts.
excerpt_separator: <!--end_excerpt-->


### TITLE TAG SETTINGS

# A short description for use in the title tag when the page title is absent; defaults to null.
tagline:           A Jekyll theme based on Eventually by HTML5 UP

# The string between the site and page title (or tagline) in the title tag; defaults to " | ".
title_separator:   " | "

# Title tag sequence. Enter "site" to display the site title first; defaults to "page".
# NOTE: When the page title is absent and a tagline is present, the tagline always comes last.
title_sequence:    page  


### THEME SETTINGS

# This enables use of the Eventually Deluxe theme.
theme:             jekyll-theme-eventually-deluxe

# Theme colors (NOTE: Hex values must be in quotes!)
colors:

  # The webpage background color; defaults to "#000000".
  body:            "#000000"

  # The color of unaccented text; defaults to "#ffffff".
  text:            "#ffffff"

  # The accent color for links and buttons; defaults to "#1cb495".
  accent:          "#1cb495"

  # The border color; defaults to "#ffffff".
  border:          "#ffffff"

# Font settings
font:

  # The font family to use; defaults to "'Roboto', sans-serif".
  family:          "'Roboto', sans-serif"

  # Font weights
  weight:

    # The font weight for normal text; defaults to 400.
    normal:        400

    # The font weight for bold text; defaults to 700.
    bold:          700

# The URL for the webfonts to use for the site; defaults to Roboto from Google.
webfonts_url:      "https://fonts.googleapis.com/css?family=Roboto:400,700"

# This enables loading of Font Awesome icon fonts; leave blank to disable.
# NOTE: This must be enabled to show the social media icons in the footer.
use_fa_fonts:      true  

# This enables display of the mailing list signup form; leave blank to disable.
# NOTE: Currently the form won't do anything unless the JS is modified to specify handling.
signup_form:       true

# Background slideshow settings
slideshow:

  # Slideshow images
  images:

    # Add a 'filename' and an 'alignment' for each image to be displayed in the slideshow.
    # The filename should be a path relative to 'site.image_source' (see above).
    # The alignment may be "left", "center", or "right"; defaults to "center".
	# NOTE: Use the following settings to render the images for the demo site.
    - filename:    bg01.jpg
      alignment:   center

    - filename:    bg02.jpg
      alignment:   center

    - filename:    bg03.jpg
      alignment:   center

  # The amount of time to wait (in milliseconds) between transitions; defaults to "6000".
  # NOTE: This must be at least twice as long as the transition speed (3000 milliseconds). 
  delay:           6000

# The filename of your custom CSS file; Jekyll will look for this in the '/assets/css/' directory.
custom_css:  


### SITE OWNER SETTINGS

# The name to display in the copyright notice in the site footer.
owner:             Your Name Here

# Contact link settings
contact:

  # Social media account type and link URL settings. (Accounts without a URL will be omitted.)
  accounts:

    - type:        dribbble
      link:        "#"

    - type:        facebook
      link:        "#"

    - type:        flickr
      link:  

    - type:        github
      link:        "#"

    - type:        gitlab
      link:  

    - type:        instagram
      link:        "#"

    - type:        linkedin
      link:  

    - type:        mastodon
      link:        "#"

    - type:        pinterest
      link:  

    - type:        slack
      link:  

    - type:        twitter
      link:        "#"

  # The contact email address for the site. This will also be displayed as a link.
  email:           "nobody@example.com"

  # This enables the display of contact links in the footer; leave blank to disable.
  # NOTE: Links will be displayed as text if 'site.use_fa_fonts' is disabled.
  links:           true

# Credits to be displayed after the copyright notice in the footer.
credits:

  - <a href="https://html5up.net/eventually">Eventually</a> by <a href="https://html5up.net">HTML5 UP</a>

  - Adapted for <a href="https://jekyllrb.com">Jekyll</a> by <a href="https://github.com/dcsjapan">Dominion</a>


### BUILD SETTINGS

sass:
  style:     compressed


### DEMO SITE BUILD SETTINGS
  
# The following setting enables the demo site included with this theme gem.
# NOTE: Set image_source to "/demo/images/" to see the images included in the demo.
include:
  - demo
